***
* **Full Name** = Anan Ghosh
* **UCID** = 30220833
***

| Q | Title                                                            | Points |
|---|------------------------------------------------------------------|--------|
| 1 | Heart   Disease Data Analysis using Pandas                       | 25     |
| 3 | Exploratory   Data Analysis of Environmental Sensor Measurements | 40     |
| 4 | Exploratory   Data Analysis of Engineering Services Revenue      | 35     |
|   | Total                                                            | 100    |


You can use the Table of Content on the left side of this notebook to efficiently navigate within this documents.

<font color='Red'><b>
Packages that you are allowed to use: pandas and numpy
</b></font>

* All calculations can be performed exclusively using pandas. Nonetheless, for enhanced flexibility, numpy also serves as a viable alternative for some small tasks.

# **1. Heart Disease Data Analysis using Pandas (25 pts)**

We analyze data collected from patients with heart disease to extract meaningful information. For more details about the dataset, refer to the Kaggle link provided: https://www.kaggle.com/imnikhilanand/heart-attack-prediction

![Img](https://storage.googleapis.com/kaggle-datasets-images/23651/30233/21d3eec8c2d5c04b7014f61ae3b516be/dataset-cover.jpg)


| Column    | Description                                                |
|-----------|------------------------------------------------------------|
| age       | Age in years                                               |
| sex       | Sex (1 = male; 0 = female)                                 |
| cp        | Chest pain type                                           |
| trestbps  | Resting blood pressure (in mm Hg on admission)            |
| chol      | Serum cholestoral in mg/dl                                |
| fbs       | Fasting blood sugar > 120 mg/dl (1 = true; 0 = false)     |
| restecg   | Resting electrocardiographic results                       |
| thalach   | Maximum heart rate achieved                               |
| exang     | Exercise-induced angina (1 = yes; 0 = no)                 |
| oldpeak   | ST depression induced by exercise relative to rest        |
| slope     | The slope of the peak exercise ST segment                  |
| ca        | Number of major vessels (0-3) colored by fluoroscopy       |
| thal      | Thalassemia (3 = normal; 6 = fixed defect; 7 = reversible defect) |
| num       | Diagnosis of heart disease (angiographic disease status)  |

Please see [this link](https://www.kaggle.com/datasets/imnikhilanand/heart-attack-prediction) for a full description of the dataset attribute explanansions.




**Tasks:**

**Report 1: Average Age of Patients**
- Calculate and report the average age of patients in the dataset.

**Report 2: Average Cholesterol Levels in Age Intervals**
- Divide patients into age intervals of 10 years each ([20, 30), [30, 40), [40, 50), [50, 60)).
- Calculate and report the average cholesterol (chol) levels for each age interval.

**Report 3: Average Resting Blood Pressure in Extreme Cholesterol Levels**
- Identify patients with the highest 30% and lowest 30% cholesterol levels in the dataset.
- Calculate and report the average resting blood pressure (trestbps) for patients in these two groups.

**Report 4: Percentage of Men and Women with Positive Heart Disease Diagnosis**
- Calculate and report the percentage of men and women with a positive diagnosis of heart disease (num=1).

In [ ]:
# =============================================================================
# Read the dataset
# =============================================================================
# The original dataset is available at the following link:
# https://www.kaggle.com/datasets/imnikhilanand/heart-attack-prediction
# For ease of access, the dataset has been uploaded on GitHub
url = 'https://raw.githubusercontent.com/HatefDastour/ENGG_680/main/Assignment_03/heart_data.csv'

import pandas as pd

# Load the data from 'heart_data.csv' into a DataFrame.
# Specify that there is no index column and the first row contains headers.
# Treat "?" as NaN (missing values).
df = pd.read_csv(url, na_values="?")

# Remove extra spaces before and after column names
df.columns = df.columns.str.strip()

# Display the first few rows of the DataFrame
display(df.head())

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,num
0,28,1,2,130.0,132.0,0.0,2.0,185.0,0.0,0.0,NaN,NaN,NaN,0
1,29,1,2,120.0,243.0,0.0,0.0,160.0,0.0,0.0,NaN,NaN,NaN,0
2,29,1,2,140.0,NaN,0.0,0.0,170.0,0.0,0.0,NaN,NaN,NaN,0
3,30,0,1,170.0,237.0,0.0,1.0,170.0,0.0,0.0,NaN,NaN,6.0,0
4,31,0,2,100.0,219.0,0.0,1.0,150.0,0.0,0.0,NaN,NaN,NaN,0

***
**Your Contribution**

Please make sure that add comments for the readiblity of your code.

***

In [ ]:
# Your Contribution

#1
avg_age = df["age"].mean() #calculating the avarage age by mean from dataset
print("Average Age: ",avg_age) #print the avarage age
print('\n')

#2
bins = [20, 30, 40, 50, 60]
df['age_group'] = pd.cut(df["age"], bins,right = False) #define the age interval

ave_chol_age_group = df.groupby("age_group")["chol"].mean() #grouped by the age interval and calculate the avg chol in those age interval
print('Average Cholesterol by Age Group: ',ave_chol_age_group)  #print avarage Cholesterol by age group
print('\n')

#3
df = df.sort_values('chol') #sort the dataframe according to Cholesterol

highest = df.head((int(len(df)* (30/100))))
lowest = df.tail((int(len(df)* (30/100))))

#print the dataframe for highest 30% and lowest 30%
print("highest_30%\n")
display(highest)
print('\n\n')
print("lowest_30%\n")
display(lowest)


# Calculate and report the average resting blood pressure for these two groups
avg_trestbps_highest = highest['trestbps'].mean()
avg_trestbps_lowest = lowest['trestbps'].mean()

# print the results
print("Average trestbps for patients with the highest 30% cholesterol levels:", avg_trestbps_highest)
print("Average trestbps for patients with the lowest 30% cholesterol levels:", avg_trestbps_lowest)


#4
diagnoses_by_sex= df.groupby("sex")["num"].mean() #grouped by sex and calculate avg positive heart disease by sex

# Display the percentage of positive diagnoses for each gender
print("Percentage of men with a positive diagnosis of heart disease:" , diagnoses_by_sex[1] * 100, "%")
print("Percentage of women with a positive diagnosis of heart disease:", diagnoses_by_sex[0] * 100, "%")

Average Age:  47.826530612244895


Average Cholesterol by Age Group:  age_group
[20, 30)    187.500000
[30, 40)    239.630435
[40, 50)    250.131313
[50, 60)    256.210526
Name: chol, dtype: float64


highest_30%

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,num,age_group
170,56,1,4,120.0,85.0,0.0,0.0,140.0,0.0,0.0,NaN,NaN,NaN,0,"[50, 60)"
128,52,1,2,140.0,100.0,0.0,0.0,138.0,1.0,0.0,NaN,NaN,NaN,0,"[50, 60)"
196,38,1,4,92.0,117.0,0.0,0.0,134.0,1.0,2.5,2.0,NaN,NaN,1,"[30, 40)"
114,50,1,4,140.0,129.0,0.0,0.0,135.0,0.0,0.0,NaN,NaN,NaN,0,"[50, 60)"
0,28,1,2,130.0,132.0,0.0,2.0,185.0,0.0,0.0,NaN,NaN,NaN,0,"[20, 30)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69,44,1,2,130.0,215.0,0.0,0.0,135.0,0.0,0.0,NaN,NaN,NaN,0,"[40, 50)"
112,50,1,2,140.0,216.0,0.0,0.0,170.0,0.0,0.0,NaN,NaN,3.0,0,"[50, 60)"
132,53,0,2,140.0,216.0,0.0,0.0,142.0,1.0,2.0,2.0,NaN,NaN,0,"[50, 60)"
216,54,1,4,125.0,216.0,0.0,0.0,140.0,0.0,0.0,NaN,NaN,NaN,1,"[50, 60)"
267,54,1,4,140.0,216.0,0.0,0.0,105.0,0.0,1.5,2.0,NaN,NaN,1,"[50, 60)"

lowest_30%

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,num,age_group
266,53,1,4,180.0,285.0,0.0,1.0,120.0,1.0,1.5,2.0,NaN,NaN,1,"[50.0, 60.0)"
179,59,1,2,140.0,287.0,0.0,0.0,150.0,0.0,0.0,NaN,NaN,NaN,0,"[50.0, 60.0)"
212,50,0,3,140.0,288.0,0.0,0.0,140.0,1.0,0.0,NaN,NaN,7.0,1,"[50.0, 60.0)"
280,43,1,4,140.0,288.0,0.0,0.0,135.0,1.0,2.0,2.0,NaN,NaN,1,"[40.0, 50.0)"
253,44,1,2,150.0,288.0,0.0,0.0,150.0,1.0,3.0,2.0,NaN,NaN,1,"[40.0, 50.0)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
226,38,1,4,110.0,NaN,0.0,0.0,150.0,1.0,1.0,2.0,NaN,NaN,1,"[30.0, 40.0)"
239,52,1,4,170.0,NaN,0.0,0.0,126.0,1.0,1.5,2.0,NaN,NaN,1,"[50.0, 60.0)"
244,54,1,4,140.0,NaN,0.0,0.0,118.0,1.0,0.0,NaN,NaN,NaN,1,"[50.0, 60.0)"
275,59,1,4,130.0,NaN,0.0,0.0,125.0,0.0,0.0,NaN,NaN,NaN,1,"[50.0, 60.0)"
278,66,1,4,140.0,NaN,0.0,0.0,94.0,1.0,1.0,2.0,NaN,NaN,1,NaN

Average trestbps for patients with the highest 30% cholesterol levels: 133.13636363636363
Average trestbps for patients with the lowest 30% cholesterol levels: 136.5977011494253
Percentage of men with a positive diagnosis of heart disease: 44.13145539906103 %
Percentage of women with a positive diagnosis of heart disease: 14.814814814814813 %

**Contribution Explaination**

avg_age = df["age"].mean(): This line calculates the average age of the individuals in the dataset by taking the mean of the "age" column.

bins = [20, 30, 40, 50, 60]: This line defines bins for age intervals. It seems like it's dividing the age range into intervals from 20-29, 30-39, 40-49, and 50-59.

df['age_group'] = pd.cut(df["age"], bins, right=False): Here, it creates a new column in the dataset called "age_group" by categorizing each individual's age into one of the specified bins based on their "age" column values.

ave_chol_age_group = df.groupby("age_group")["chol"].mean(): This line groups the dataset by the "age_group" column and calculates the average cholesterol ("chol") level for each age group.

df = df.sort_values('chol'): This line sorts the dataset based on the "chol" column in ascending order, which is cholesterol level.

highest = df.head((int(len(df)* (30/100))): It extracts the top 30% of the dataset, individuals with the highest cholesterol levels.

lowest = df.tail((int(len(df)* (30/100))): It extracts the bottom 30% of the dataset, individuals with the lowest cholesterol levels.

The subsequent code prints these two subsets and calculates and prints the average resting blood pressure ("trestbps") for both groups.

diagnoses_by_sex = df.groupby("sex")["num"].mean(): This code groups the dataset by the "sex" column and calculates the average number ("num") of positive diagnoses of heart disease for each gender (assuming "1" represents a positive diagnosis).

The code then prints the percentage of men and women with a positive diagnosis of heart disease.

# **2. Exploratory Data Analysis of Environmental Sensor Measurements (40 pts)**

**Dataset:** You are provided with a dataset named "sensor_data.csv" containing measurements from various environmental sensors. The dataset consists of the following columns:

- `time`: Timestamp of the measurement.
- `power`: Power consumption (in watts).
- `temp`: Temperature (in Celsius).
- `humidity`: Humidity level (in percentage).
- `light`: Light intensity (in lux).
- `CO2`: Carbon dioxide concentration (in ppm).
- `dust`: Dust concentration (in micrograms per cubic meter).

**Tasks:**
1. **Data Loading and Initial Inspection:**
   - Display the data types of each column.
   - Display the number of unique values in the `time` column.

2. **Data Preprocessing:**
   - Convert the `time` column to a datetime format.
   - Drop duplicate rows if any.

3. **Data Analysis:**
   - Calculate and display the average power consumption on weekdays and weekends separately.
   - Create a new column named `CO2_category` with categories: 'Low', 'Medium', and 'High' based on CO2 concentration as follows:
$$
\text{CO2_categories}(x) =
\begin{cases}
\text{Low} & \text{if } 0 \leq x < 500 \\
\text{Medium} & \text{if } 500 \leq x < 1000 \\
\text{High} & \text{if } x \geq 1000
\end{cases}
$$
This mathematical representation describes how the categories 'Low,' 'Medium,' and 'High' are assigned based on the input value $x$.

   - Calculate the mean power consumption for each CO2 category.

4. **Data Manipulation:**
   - Calculate the cumulative sum of power consumption on a rolling window of 3 hours.
   - Create a new column named `temp_change` that represents the change in temperature from the previous row.

---
**Understanding Rolling Window:**
   A rolling window operation involves calculating a function (in this case, the cumulative sum) over a moving subset of data points within a specified window size. For example, with a window size of 3 hours, the cumulative sum will be calculated for every 3 consecutive hours of power consumption data. See this link for more details. https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.rolling.html

---

In [ ]:
# =============================================================================
# Read the dataset
# =============================================================================

import pandas as pd

# Download the dataset from a specific URL
url = "https://raw.githubusercontent.com/HatefDastour/ENGG_680/main/Assignment_03/sensor_data.csv"

# Load the data from 'sensor_data.csv' into a DataFrame.
df = pd.read_csv(url)

# Display the first few rows of the DataFrame
display(df.head())

                  time  power  temp  humidity  light  CO2   dust
0  2015-08-01 00:00:28    0.0    32        40      0  973  27.80
1  2015-08-01 00:00:58    0.0    32        40      0  973  27.09
2  2015-08-01 00:01:28    0.0    32        40      0  973  34.50
3  2015-08-01 00:01:58    0.0    32        40      0  973  28.43
4  2015-08-01 00:02:28    0.0    32        40      0  973  27.58

***
**Your Contribution**

Please make sure that add comments for the readiblity of your code.

***

In [ ]:
# Your Contribution

#1
for col in df.columns:     #ittrative through dataframe columns
  print(f"{col}_data_type = ", type(col))    #check the each columns type and print it


time_col_unique = len(df['time'].unique()) #Checking the length of unique values

print("Number of unique values in the time column ",time_col_unique) #print the length of unique values


#2
df['time'] = pd.to_datetime(df.time, format='%Y-%m-%d %H:%M:%S')   #converting time col into datetime format

df.head(10)

df = df.drop_duplicates() #drop duplicate rows

df.head()


#3

# Create a column to identify weekdays and weekends
df['Day_of_Week'] = df['time'].dt.dayofweek
df['Weekend'] = (df['Day_of_Week'] >= 5)

# Calculate the mean power consumption for weekdays and weekends separately
weekday_avg_power = df[~df['Weekend']]['power'].mean()
weekend_avg_power = df[df['Weekend']]['power'].mean()


# Create the 'CO2_category' column
df['CO2_category'] = pd.cut(df['CO2'], bins=[0, 500, 1000, float('inf')], labels=['Low', 'Medium', 'High'])


# Calculate the mean power consumption for each CO2 category
co2_avg_power = df.groupby('CO2_category')['power'].mean()
print(co2_avg_power)

#4

df.set_index('time', inplace=True)
df['Cumulative_Power_Consumption'] = df['power'].rolling('3H').sum()  # Calculate the cumulative sum of power consumption on a rolling 3-hour window


df['temp_change'] = df['temp'].diff()    # Calculate the change in temperature from the previous row

df.head()

time_data_type =  <class 'str'>
power_data_type =  <class 'str'>
temp_data_type =  <class 'str'>
humidity_data_type =  <class 'str'>
light_data_type =  <class 'str'>
CO2_data_type =  <class 'str'>
dust_data_type =  <class 'str'>
Number of unique values in the time column  88680
CO2_category
Low            NaN
Medium    0.116968
High     -0.453846
Name: power, dtype: float64

,power,temp,humidity,light,CO2,dust,Day_of_Week,Weekend,CO2_category,Cumulative_Power_Consumption,temp_change
time,,,,,,,,,,,
2015-08-01 00:00:28,0.0,32,40,0,973,27.80,5,True,Medium,0.0,NaN
2015-08-01 00:00:58,0.0,32,40,0,973,27.09,5,True,Medium,0.0,0.0
2015-08-01 00:01:28,0.0,32,40,0,973,34.50,5,True,Medium,0.0,0.0
2015-08-01 00:01:58,0.0,32,40,0,973,28.43,5,True,Medium,0.0,0.0
2015-08-01 00:02:28,0.0,32,40,0,973,27.58,5,True,Medium,0.0,0.0

**Contribution Explaination**

for col in df.columns:: This loop iterates through the columns of the DataFrame df.

print(f"{col}_data_type = ", type(col)): For each column, it prints the column name followed by its data type. However, there is an issue in this line. It should check the data type of the column values, not the column name. To do that, you should use type(df[col]) instead of type(col).

time_col_unique = len(df['time'].unique()): It calculates the number of unique values in the "time" column and stores it in the variable time_col_unique. The result is not printed in the code.

df['time'] = pd.to_datetime(df.time, format='%Y-%m-%d %H:%M:%S'): This line converts the "time" column to a datetime format based on the specified format. It assumes that the "time" column contains date and time information in the "YYYY-MM-DD HH:MM:SS" format.

df.head(10): It prints the first 10 rows of the DataFrame after the conversion.

df = df.drop_duplicates(): This line drops duplicate rows from the DataFrame.

It creates new columns in the DataFrame:

Day_of_Week: It extracts the day of the week (0 for Monday, 1 for Tuesday, etc.) from the "time" column using the dt.dayofweek attribute.

Weekend: It creates a Boolean column that identifies whether a day falls on a weekend (Saturday or Sunday) based on the "Day_of_Week" column.

weekday_avg_power and weekend_avg_power: These variables store the average power consumption for weekdays and weekends, respectively. The code calculates the mean power consumption for both categories.

CO2_category: It creates a new column that categorizes CO2 levels into "Low," "Medium," or "High" based on specified bins.

co2_avg_power: This code calculates the mean power consumption for each CO2 category using a groupby operation and prints the result.

df.set_index('time', inplace=True): It sets the "time" column as the index of the DataFrame.

df['Cumulative_Power_Consumption']: This line calculates the cumulative sum of power consumption on a rolling 3-hour window.

df['temp_change']: It calculates the change in temperature from the previous row by taking the difference between consecutive "temp" values.

df.head(): It prints the first few rows of the DataFrame with the new columns added.

# **3. Exploratory Data Analysis of Engineering Services Revenue (35 pts)**

**Objective:** In this assignment, you will download a dataset from a specified URL, extract a zip file, read a CSV file, and perform exploratory data analysis using Python and Pandas.

**Dataset:** The dataset you'll be using is provided as a zip file at this URL: [Download Dataset](https://www150.statcan.gc.ca/n1/tbl/csv/21100163-eng.zip). The zip file contains a CSV file named "21100163.csv".

**Tasks:**
1. **Exploratory Data Analysis:**
   - Import the necessary libraries: **pandas**.
   - Read the "21100163.csv" file into a DataFrame named `df`.
   - Display the first 5 rows of the DataFrame.

1. **Data Analysis for Specific Regions:**
   - For each of the following regions: **Canada** and **Alberta**
     - Filter the DataFrame to include only rows with the NAICS code "Engineering services [54133]" and the specified region.
     - Group the data by 'REF_DATE' and 'Summary statistics', and sum the 'VALUE' column.
     - [Pivot](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.pivot.html) the grouped data to create a summary table with 'Summary statistics' as the index and years as columns.
     - Move the row with 'Operating profit margin' to the last row of the index.
     - Display the summary table for each region.


***
Pivoting a DataFrame involves restructuring it based on specified index or column values to produce a new organized DataFrame. See the details here:
https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.pivot.html
***

In [ ]:
# Download the ZIP file containing the data from the provided URL using wget
!wget -N https://www150.statcan.gc.ca/n1/tbl/csv/21100163-eng.zip

# Unzip the downloaded ZIP file to extract the contents
!unzip -o 21100163-eng.zip

# Remove the downloaded zip file after extraction
!rm -r 21100163-eng.zip

--2023-10-24 20:14:40--  https://www150.statcan.gc.ca/n1/tbl/csv/21100163-eng.zip
Resolving www150.statcan.gc.ca (www150.statcan.gc.ca)... 167.44.105.20
Connecting to www150.statcan.gc.ca (www150.statcan.gc.ca)|167.44.105.20|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 7325 (7.2K) [application/zip]
Saving to: ‘21100163-eng.zip’

21100163-eng.zip    100%[===================>]   7.15K  --.-KB/s    in 0s

2023-10-24 20:14:41 (2.70 GB/s) - ‘21100163-eng.zip’ saved [7325/7325]

Archive:  21100163-eng.zip
  inflating: 21100163.csv
  inflating: 21100163_MetaData.csv

***
**Your Contribution**

Please make sure that add comments for the readiblity of your code.

***

In [ ]:
# Your Contribution

#1
import pandas as pd

#Read the CSV file into a DataFrame
df = pd.read_csv("21100163.csv")


print("First 5 rows of the DataFrame:")
display(df.head())


#2

# Filter the DataFrame for Canada and Engineering services [54133]
canada_df = df[(df['GEO'] == 'Canada') & (df['North American Industry Classification System (NAICS)'] == 'Engineering services [54133]')]


# Group by 'REF_DATE' and 'Summary statistics', and sum the 'VALUE' column
canada_grouped = canada_df.groupby(['REF_DATE', 'Summary statistics'])['VALUE'].sum().reset_index()

# Pivot the grouped data
canada_pivot = canada_grouped.pivot(index='Summary statistics', columns='REF_DATE', values='VALUE')

# Move the row with 'Operating profit margin' to the last row
if 'Operating profit margin' in canada_pivot.index:
  operating_margin_row = canada_pivot.loc['Operating profit margin']
  canada_pivot = canada_pivot.drop(index='Operating profit margin')
  canada_pivot = canada_pivot.append(operating_margin_row)

# Display the summary table for Canada
print("\nSummary table for Canada:")
display(canada_pivot)



# Filter the DataFrame for Alberta and Engineering services [54133]
alberta_df = df[(df['GEO'] == 'Alberta') & (df['North American Industry Classification System (NAICS)'] == 'Engineering services [54133]')]

# Group by 'REF_DATE' and 'Summary statistics', and sum the 'VALUE' column
alberta_grouped = alberta_df.groupby(['REF_DATE', 'Summary statistics'])['VALUE'].sum().reset_index()

# Pivot the grouped data
alberta_pivot = alberta_grouped.pivot(index='Summary statistics', columns='REF_DATE', values='VALUE')


# Move the row with 'Operating profit margin' to the last row
if 'Operating profit margin' in alberta_pivot.index:
  operating_margin_row = alberta_pivot.loc['Operating profit margin']
  alberta_pivot = alberta_pivot.drop(index='Operating profit margin')
  alberta_pivot = alberta_pivot.append(operating_margin_row)


# Display the summary table for Alberta
print("\nSummary table for Alberta:")
display(alberta_pivot)

First 5 rows of the DataFrame:

,REF_DATE,GEO,DGUID,North American Industry Classification System (NAICS),Summary statistics,UOM,UOM_ID,SCALAR_FACTOR,SCALAR_ID,VECTOR,COORDINATE,VALUE,STATUS,SYMBOL,TERMINATED,DECIMALS
0,2012,Canada,2016A000011124,Engineering services [54133],Operating revenue,Dollars,81,millions,6,v99920202,1.1.1,28960.0,NaN,NaN,NaN,1
1,2012,Canada,2016A000011124,Engineering services [54133],Operating expenses,Dollars,81,millions,6,v99920203,1.1.2,25701.5,NaN,NaN,NaN,1
2,2012,Canada,2016A000011124,Engineering services [54133],"Salaries, wages, commissions and benefits",Dollars,81,millions,6,v99920204,1.1.3,11488.3,NaN,NaN,NaN,1
3,2012,Canada,2016A000011124,Engineering services [54133],Operating profit margin,Percent,239,units,0,v99920205,1.1.4,11.3,NaN,NaN,NaN,1
4,2012,Newfoundland and Labrador,2016A000210,Engineering services [54133],Operating revenue,Dollars,81,millions,6,v99920206,2.1.1,470.7,NaN,NaN,NaN,1

Summary table for Canada:

<ipython-input-6-e0f61f7479a5>:30: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  canada_pivot = canada_pivot.append(operating_margin_row)

REF_DATE,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
Summary statistics,,,,,,,,,,
Operating expenses,25701.5,28731.7,28906.7,28041.1,27032.4,25294.1,26205.3,29813.0,30738.6,32279.3
Operating revenue,28960.0,32271.3,33100.3,30806.8,29295.7,28141.0,28997.3,33153.1,33637.0,35145.7
"Salaries, wages, commissions and benefits",11488.3,11646.4,12063.7,12232.7,12249.3,11484.3,12425.8,14198.7,14016.1,14733.2
Operating profit margin,11.3,11.0,12.7,9.0,7.7,10.1,9.6,10.1,8.6,8.2

Summary table for Alberta:

<ipython-input-6-e0f61f7479a5>:52: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  alberta_pivot = alberta_pivot.append(operating_margin_row)

REF_DATE,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
Summary statistics,,,,,,,,,,
Operating expenses,8888.2,11698.9,12789.6,10584.0,9521.3,7252.2,5738.3,6732.6,7154.3,6959.2
Operating revenue,10038.8,13361.9,14307.1,11511.1,9987.6,8071.5,6349.7,7886.0,7973.5,7752.0
"Salaries, wages, commissions and benefits",3565.0,3586.7,3940.7,3502.5,3494.4,2620.3,2521.3,2792.0,2931.4,2903.9
Operating profit margin,11.5,12.4,10.6,8.1,4.7,10.2,9.6,14.6,10.3,10.2

**Contribution Explaination**


The pd.read_csv("21100163.csv") line reads the data from a CSV file named "21100163.csv" and stores it in a pandas DataFrame called df. This creates a structured, tabular representation of the data that can be easily manipulated and analyzed.

df.head() is used to display the first 5 rows of the DataFrame. This provides an initial glimpse of the dataset, helping you understand its structure and content.

Data Analysis for Canada and Alberta

This section of the code focuses on specific data analysis tasks for the regions of Canada and Alberta:

Filtering Data:

The code filters the DataFrame df to select only the rows that match specific conditions. In this case, it selects rows where 'GEO' (region) is 'Canada' and 'North American Industry Classification System (NAICS)' is 'Engineering services [54133]'. This filtering helps narrow down the data to specific regions and industry types. Grouping and Aggregating:

After filtering, the code groups the filtered data using groupby. It groups the data by 'REF_DATE' (time) and 'Summary statistics' columns. Then, it calculates the sum of the 'VALUE' column for each group. This step aggregates the data, summing up the values for different time points and types of summary statistics.

Pivoting Data:

Next, the code pivots the grouped data using pivot. It sets 'Summary statistics' as the index and 'REF_DATE' (years) as columns. This reshapes the data into a table format.

Reordering Rows:

The code reorders the rows in the summary table. Specifically, it moves the row labeled 'Operating profit margin' to the last row of the index. This row reordering is done for presentation and readability purposes.

Displaying the Summary Table:

Finally, the code displays the summary table for the specified region, in this case, Canada and Alberta. The summary table provides a concise overview of the aggregated data, showing how different summary statistics change over time.

In [ ]:
# The End